### ISSUE TITLE
lock on main menu with error

### ISSUE THREAD

**Issue by linkssy2** [VisualError/Physics-Items#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**
should be able to move through main menu

**Screenshots**
<img width="833" alt="Capture" src="https://github.com/VisualError/Physics-Items/assets/122309701/cd6d2c9c-eff0-4984-bfcb-056263dac3fc">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version [e.g v49]
 - Mod Version [e.g. 22]

**Additional context**

**Comment by linkssy2** [comment]
narrowed it down to LootableMusicTapes, this is the mod causing issues

**Comment by VisualError** [comment]
Will be fixed in v0.1.3. 

Please close this issue once the update has been release and it works fine :)
