### ISSUE TITLE
Pushing effect affecting every player in lobby

### ISSUE THREAD

**Issue by XenoX6080** [VisualError/Physics-Items#3]
**Bug description:**
This bug is about the push mechanic which gives you an effect which you slows down and lose stamina (underwater/mud mechanic). When one player pushes an item the effect applies on every player. I had a situation where one player was pushing the loot pile for a good minute just to troll us on the ship and everyone had that effect and it was unplayable. 

**Expected behavior:**
The effect should apply for the player who pushes the item, not for everyone.

**Desktop:**
 - OS: Windows 10
 - Game Version v49
 - Mod Version v0.1.22

**Comment by VisualError** [comment]
Should hopefully be fixed on v0.1.3
