### ISSUE TITLE
Random push effect while the player collision is disabled

### ISSUE THREAD

**Issue by XenoX6080** [VisualError/Physics-Items#4]
**Describe the bug**
I'm not sure how it does that, but I had my friend getting the push effect while the player collision was off, no idea what he did to make this happen. Upon asking he answered me that "it just did by itself".

**Desktop:**
 - OS: Windows 10
 - Game Version v49
 - Mod Version v0.1.22

**Comment by VisualError** [comment]
I can't really work on this with the current information. But I'll try to have this fixed for the next patch

**Comment by XenoX6080** [comment]
since the slowness effect has been removed im closing this
