### ISSUE TITLE
Making the collision sound differentiate from each other.

### ISSUE THREAD

**Issue by XenoX6080** [VisualError/Physics-Items#5]
**Is your feature request related to a problem? Please describe.**
The same exact sound can be annoying at some point, so I would make it that the sound can have different pitch each collision.

**Describe the solution you'd like**
Before the sound is produced make it filter by pitch randomizer to make each sound "unique" consistent and plain.

**Describe alternatives you've considered**
None, I think.

**Comment by VisualError** [comment]
This will be added to v0.1.3, thanks for the suggestion!

**Comment by VisualError** [comment]
v0.1.3 is released now
